fix: allow institutional managers to edit users from their institutions
pressbooks/pressbooks-multi-institution pull request #121
Opened 2024-03-21 13:01 UTC by richard015ar

This PR would fix https://github.com/pressbooks/pressbooks-multi-institution/issues/120 but @arzola is working on a [refactor](https://github.com/pressbooks/pressbooks-multi-institution/issues/76) of this class. It is just to show him where the problem is, that might help him to apply the necessary changes to his new implementation.

2024-03-21 13:06 UTC, richard015ar commented on src/Actions/PermissionsManager.php
> -                    $isAccessAllowed = false;
It is false by default for `user-edit.php` page, since it won't meet this condition https://github.com/pressbooks/pressbooks-multi-institution/pull/121/files#diff-c16b712644fb16982b2669cf48af33f13f5621263e53e518834934309434bd87L328, so we need to explicitly declare it true in this case.

2024-03-27 15:10 UTC, arzola requested changes
It requires to handle also the post method to handle the save action

2024-03-27 15:10 UTC, arzola commented on src/Actions/PermissionsManager.php
> -                    $isAccessAllowed = false;
I think this should be $_REQUEST instead to allow the form to be saved too

```
if (isset($_REQUEST['user_id']) && in_array($_REQUEST['user_id'], $institutionalUsers)) {
                    $isAccessAllowed = true;
                }
```

2024-03-27 18:30 UTC, arzola approved these changes
LGTM

2024-03-27 18:30 UTC, merged