chore: refactor
pressbooks/pressbooks-multi-institution pull request #125
Opened 2024-03-25 21:00 UTC by arzola

2024-03-27 18:57 UTC, richard015ar commented on src/Services/PermissionsManager.php
> +    public function handlePagesPermissions($institution, $institutionalManagers, $institutionalUsers): void
It's not mandatory for the current PR. But just leaving notes here and there to think about it later as a team (and create issues if needed).

This method is huge! I don't know exactly how we can split it into shorter methods for maintainability, separation of concerns and readability tbh. 
The inline method within the `admin_init` that restricts the access can be a separate method.

In my mind I was thinking something like:
```php
add_action('admin_init', [$this, 'handleAdminInit']); //(maybe in setupFilters method?)

protected function handlePagesRestricction() {
    $allowedBooks = $this->getAllowedBooks();
    $this->restrictAccessToPages($allowedBooks);
}

private function getAllowedBooks() {
   if ($institution === 0) {
        return;
    }

    return InstitutionBook::query()
        ->select('blog_id')
        ->where('institution_id', $institution)
        ->get()
        ->map(fn ($book) => $book->blog_id)
        ->toArray();
}

private function restrictAccessToPages($allowedBooks) {
    // Moved the logic here
}
```

But I am not sure. Let's see if Dalcin has a better idea.

2024-03-27 18:58 UTC, richard015ar commented on src/Views/BaseInstitutionList.php
> +    abstract public function addColumns(array $columns): array;
nice approach!

2024-03-28 11:22 UTC, richard015ar commented on src/Actions/TableViews.php
> +                    'institutions' => Institution::query()->whereHas('books')->orderBy('name')->get(),
We need to implement here a dynamic `whereHas` parameter since it can be `books` or `users` depending on the current page.

2024-03-28 11:25 UTC, richard015ar commented on src/Services/MenuManager.php
> +class MenuManager
later, we can move [these methods](https://github.com/pressbooks/pressbooks-multi-institution/pull/124/files) to this class. I can do that if you are ok with it.

2024-03-28 11:28 UTC, richard015ar commented on src/Views/UserList.php
> +        return "({$idSubQuery->toSql()}) as institution_id, ({$nameSubQuery->toSql()}) as institution";
nicely done, bro!

2024-03-28 11:49 UTC, richard015ar commented on tests/Feature/Services/PermissionsManagerTest.php
> +        add_filter('wp_redirect', [$this, 'captureRedirect'], 10, 2);
cool! I spent some hours trying to test other features on pressbooks/pressbooks and oidc/saml with wp_redirect and I never thought about it. Taking notes from this for testing LTI / Launch actions.

2024-03-28 14:30 UTC, fdalcin requested changes
LGTM so far for what I can see. Agree with the points mentioned by @richard015ar.

While testing however, I've identified a bug that is also replicable on `dev.pressbooks.netwwork`. There are a couple of pages in the book context that institutional managers can't access, see the video below:

https://github.com/pressbooks/pressbooks-multi-institution/assets/1761690/4d57061b-2020-4b46-919d-c99cbddfd3fe

Team agreed to include the fix in the current PR.

2024-03-28 14:30 UTC, fdalcin commented on src/Actions/TableViews.php
> +                    'institutions' => Institution::query()->whereHas('books')->orderBy('name')->get(),
+1

2024-03-28 19:06 UTC, richard015ar approved these changes
LGTM!

2024-03-28 19:07 UTC, merged