fix: a11y improvements
pressbooks/pressbooks-multi-institution pull request #155
Opened 2024-04-09 18:23 UTC by richard015ar

Issue: https://github.com/pressbooks/pressbooks-multi-institution/issues/129

This PR addresses some of the suggestions mentioned in: https://github.com/pressbooks/pressbooks-multi-institution/issues/129.

2024-04-10 11:07 UTC, richard015ar commented on resources/assets/styles/pressbooks-multi-institutions.css
> +table.institutions-totals-table {
it is ok to create class names with `-`? I was unsure if I should use `_` o `-`

2024-04-10 11:39 UTC, greatislander commented on resources/assets/styles/pressbooks-multi-institutions.css
> +table.institutions-totals-table {
Either is fine, I tend to prefer kebab case for this kind of situation.

2024-04-11 00:32 UTC, greatislander requested changes
Two suggested changes.

One other issue is that I realized that the button which dismisses the error notice is included in the announced message because I think WordPress inserts it dynamically after load just like the other content is inserted. This is what's announced when I try to create two institutions both called "Dal":

<img width="649" alt="VoiceOver output which reads: Dismiss this notice. Error: the form is invalid. An institution with the name Dal already exists. Please use a different name." src="https://github.com/pressbooks/pressbooks-multi-institution/assets/605361/27c5128b-8fde-47c7-8f99-53cdce16667c">

I would suggest for these you could remove the `is-dismissable` class. WordPress adds `role="alert"` to them dynamically so creating a live region within the notice that doesn't include the dismiss button wouldn't work.

2024-04-11 00:32 UTC, greatislander commented on resources/views/institutions/form.blade.php
> +							inputmode="numeric" pattern="[0-9]*"
This needs a `type="text"` to pick up the default input styling. Right now it looks a little funny.

<img width="662" alt="Screenshot showing improperly styled input" src="https://github.com/pressbooks/pressbooks-multi-institution/assets/605361/a884d184-402c-4d04-96c1-7c15e6c5e711">

2024-04-11 00:32 UTC, greatislander commented on resources/views/institutions/form.blade.php
> +							title="{{ __('Only numbers are allowed', 'pressbooks-multi-institution') }}"
I would avoid using a `title` as this is not consistently supported. I'd suggest instead adding a visually hidden `<div>` with idea and referencing it in the `aria-describedby` attribute, e.g.

```
aria-describedby="book_limit-description book_limit-input-instruction"
```

Paired with:

```blade
<div class="screen-reader-text" id="book_limit-instruction">{{ __('Only numbers are allowed', 'pressbooks-multi-institution') }}</div>
```

2024-04-11 00:32 UTC, greatislander commented on resources/views/assign/index.blade.php
> +		role="status"
This should be `role="alert"`. It also doesn't seem to be necessary as WordPress adds this dynamically/

2024-04-11 15:42 UTC, richard015ar commented
Code LGTM

2024-04-11 15:59 UTC, fdalcin approved these changes
LGTM

2024-04-11 15:59 UTC, merged